smart-education-center/Areas/Admin/Controllers/ManagePeopleController.cs
using smart_education_center.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static smart_education_center.Common.Enum;

namespace smart_education_center.Areas.Admin.Controllers
{
    public class ManagePeopleController : Controller
    {
        private CyberSchoolEntities _context = new CyberSchoolEntities();

        // GET: Admin/ManagePeople
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddStudent()
        {
            return PartialView("AddStudentPV");
        }

        [HttpPost]
        public ActionResult AddStudent(Student model)
        {
            try
            {
                using (_context)
                {
                    if (_context.Student.Any(x => x.StudentNumber == model.StudentNumber))
                    {
                        TempData["ResultCode"] = (int)ResultCode.FAILED;
                        TempData["ResultMessage"] = "The student number is already exists.";
                        return RedirectToAction("Index");
                    }
                    if (_context.Student.Any(x => x.username == model.username))
                    {
                        TempData["ResultCode"] = (int)ResultCode.FAILED;
                        TempData["ResultMessage"] = "The username is already exists.";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        Student student = new Student();
                        student = model;
                        student.RegisteredDate = DateTime.Now;
                        TempData["ResultCode"] = (int)ResultCode.SUCCESS;
                        TempData["ResultMessage"] = "Added Successfully";
                        _context.Student.Add(student);
                        _context.SaveChanges();
                    }

                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["ResultMessage"] = e.ToString();
                return RedirectToAction("Index");
            }


        }

        public ActionResult AddTeacher()
        {
            return PartialView("AddTeacherPV");
        }

        public ActionResult AddAdmin()
        {
            return PartialView("AddAdminPV");
        }

    }
}

smart-education-center/Areas/Admin/Views/ManagePeople/AddStudentPV.cshtml
@model smart_education_center.Models.Student

@{
    Layout = null;
}
<div class="modal-header site-theme" style="background-color:#343a40">
    <h4 class="modal-title pull-left" style="color:rgba(255, 255, 255, 0.5)">Add a new student</h4>
    <button type="button" class="close" data-dismiss="modal">&times;</button>
</div>
<div class="site-theme">
    @using (Html.BeginForm("AddStudent", "ManagePeople", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <form id="formAC">
            <div style="padding-right:5px;padding-left:5px;padding-bottom:5px;padding-top:5px; background-color:#ffffff">

                <div class="navbar-form div-row" style="position:center">
                    @Html.Label("Student Number (Eg: SE_001)")
                    @Html.TextBoxFor(model => model.StudentNumber, new { @class = "form-control", @required = "required" })
                </div>
                <div class="navbar-form div-row" style="position:center">
                    @Html.Label("First Name")
                    @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control", @required = "required" })
                </div>
                <div class="navbar-form div-row" style="position:center">
                    @Html.Label("Last Name")
                    @Html.TextBoxFor(model => model.LastName, new { @class = "form-control", @required = "required" })
                </div>
                <div class="navbar-form div-row" style="position:center">
                    @Html.Label("username")
                    @Html.TextBoxFor(model => model.username, new { @class = "form-control", @required = "required" })
                </div>
                <div class="navbar-form div-row" style="position:center">
                    @Html.Label("password")
                    @Html.TextBoxFor(model => model.passHash, new { @class = "form-control", @required = "required" })
                </div>
            </div>
            <div class="modal-footer site-theme">
                <button type="submit" class="btn btn-success" required>Add</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            </div>
        </form>
    }
</div>

smart-education-center/Areas/Admin/Views/ManagePeople/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<div id="wrapper">
    <div id="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-4 col-sm-4 mb-3">
                    <div class="card text-white bg-primary o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                                <i class="fas fa-fw fa-comments"></i>
                            </div>
                            <div class="mr-5">100 New Students!</div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1" href="#" onclick="addView(1)">
                            <span class="float-left">Add a new student</span>
                            <span class="float-right">
                                <i class="fas fa-angle-right"></i>
                            </span>
                        </a>
                    </div>
                </div>
                <div class="col-xl-4 col-sm-4 mb-3">
                    <div class="card text-white bg-warning o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                                <i class="fas fa-fw fa-list"></i>
                            </div>
                            <div class="mr-5">50 New Teachers!</div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1" href="#" onclick="">
                            <span class="float-left">Add a new teacher</span>
                            <span class="float-right">
                                <i class="fas fa-angle-right"></i>
                            </span>
                        </a>
                    </div>
                </div>
                <div class="col-xl-4 col-sm-4 mb-3">
                    <div class="card text-white bg-success o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                                <i class="fas fa-fw fa-shopping-cart"></i>
                            </div>
                            <div class="mr-5">2 New Administrators!</div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1" href="#" onclick="">
                            <span class="float-left">Add a new admin</span>
                            <span class="float-right">
                                <i class="fas fa-angle-right"></i>
                            </span>
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>


<!--Popup model edit and view-->
<div class="modal fade" id="popupModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body site-theme-model" id="popupModalBodyDiv">
                @*popupPV*@
            </div>
        </div>
    </div>
</div>

<script src="~/Areas/Admin/scripts/jquery.min.js"></script>
<script>

    $(document).ready(function () {

        var resultCode = @Html.Raw(Json.Encode(TempData["ResultCode"]));
        var resultMessage = @Html.Raw(Json.Encode(TempData["ResultMessage"]));

        if (resultCode == 1) {
            toastr.success(resultMessage.toString());
        }

        if (resultCode == 2) {
            toastr.error(resultMessage.toString());
        }
    });

    var addView = function (type) {

        var url = '';
        if (type==1) {
            url = '@Url.Action("AddStudent", "ManagePeople")';
        }
        if (type==2) {
            url = '@Url.Action("AddTeacher", "ManagePeople")';
        }
        if (type==3) {
            url = '@Url.Action("AddAdmin", "ManagePeople")';
        }

        $("#popupModalBodyDiv").load(url, function () {
            $("#popupModal").modal('show');
        })

    }
</script>