smart-education-center/Areas/Admin/Controllers/ManageClassController.cs
using smart_education_center.Areas.Admin.Models;
using smart_education_center.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static smart_education_center.Common.Enum;

namespace smart_education_center.Areas.Admin.Controllers
{
    public class ManageClassController : Controller
    {
        private CyberSchoolEntities _context = new CyberSchoolEntities();
        // GET: Admin/ManageClass
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddClass()
        {
            return PartialView("AddClassPV");
        }

        [HttpPost]
        public ActionResult AddClass(Grade model)
        {
            try
            {
                using (_context)
                {
                    if (_context.Grade.Any(x => x.Grade1 == model.Grade1))
                    {
                        TempData["ResultCode"] = (int)ResultCode.FAILED;
                        TempData["ResultMessage"] = "The class is already exists.";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        Grade grade = new Grade();
                        grade.Grade1 = model.Grade1;
                        grade.GradeDescription = model.GradeDescription;
                        grade.IsDeleted = (int)IsDeleted.NO;

                        _context.Grade.Add(grade);
                        _context.SaveChanges();

                        TempData["ResultCode"] = (int)ResultCode.SUCCESS;
                        TempData["ResultMessage"] = "Added Successfully";
                        return RedirectToAction("Index");
                    }
                }
            }
            catch (Exception e)
            {
                TempData["ResultCode"] = (int)ResultCode.FAILED;
                TempData["ResultCode"] = e.ToString();
                return RedirectToAction("Index");
            }
        }

        public ActionResult AddSubject()
        {
            return PartialView("AddSubjectPV");
        }

        [HttpPost]
        public ActionResult AddSubject(Subject model)
        {
            try
            {
                using (_context)
                {
                    if (_context.Subject.Any(x => x.SubjectCode == model.SubjectCode))
                    {
                        TempData["ResultCode"] = (int)ResultCode.FAILED;
                        TempData["ResultMessage"] = "The subject code is already exists.";
                        return RedirectToAction("Index");
                    }
                    if (_context.Subject.Any(x => x.SubjectName == model.SubjectName))
                    {
                        TempData["ResultCode"] = (int)ResultCode.FAILED;
                        TempData["ResultMessage"] = "The subject name is already exists.";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        Subject subject = new Subject();
                        subject.SubjectName = model.SubjectName;
                        subject.SubjectCode = model.SubjectCode;
                        subject.SubjectDescription = model.SubjectDescription;

                        subject.IsDeleted = (int)IsDeleted.NO;
                        subject.IsActive = (int)IsActive.YES;

                        _context.Subject.Add(subject);
                        _context.SaveChanges();

                        TempData["ResultCode"] = (int)ResultCode.SUCCESS;
                        TempData["ResultMessage"] = "Added Successfully";
                        return RedirectToAction("Index");
                    }
                }
            }
            catch (Exception e)
            {
                TempData["ResultCode"] = (int)ResultCode.FAILED;
                TempData["ResultCode"] = e.ToString();
                return RedirectToAction("Index");
            }
        }

        public ActionResult AssignSubject()
        {
            try
            {
                IQueryable<Grade> dbGradeList = null;
                dbGradeList = _context.Grade.Where(x => x.IsDeleted == (int)IsDeleted.NO);
                ViewBag.Grades = new SelectList(dbGradeList, "Id", "Grade1");
                //ViewBag.Subjects = new SelectList(_context.Subject.AsQueryable(), "Id", "SubjectName");
                TempData["Subjects"] = new SelectList(_context.Subject.AsQueryable(), "Id", "SubjectName");
                return PartialView("AssignSubjectPV");
            }
            catch (Exception e)
            {
                TempData["ResultCode"] = (int)ResultCode.FAILED;
                TempData["ResultMessage"] = e.ToString();
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult AssignSubject(GradeVsSubject model)
        {
            try
            {
                GradeVsSubject classSubject = model;
                classSubject.Grade = _context.Grade.FirstOrDefault(x => x.Id == model.GradeId);
                classSubject.Subject = _context.Subject.FirstOrDefault(x => x.Id == model.SubjectId);
                classSubject.Description = model.Grade.Grade1 + "'s " + model.Subject.SubjectName + " subject.";
                if (ValidateClassSubject(model))
                {
                    _context.GradeVsSubject.Add(classSubject);
                    _context.SaveChanges();

                    TempData["ResultCode"] = (int)ResultCode.SUCCESS;
                    TempData["ResultMessage"] = "Added Successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["ResultCode"] = (int)ResultCode.FAILED;
                    TempData["ResultMessage"] = "Already Exists";
                    return RedirectToAction("Index");
                }

            }
            catch (Exception e)
            {
                TempData["ResultCode"] = (int)ResultCode.FAILED;
                TempData["ResultMessage"] = e.ToString();
                return RedirectToAction("Index");
            }

        }

        private bool ValidateClassSubject(GradeVsSubject model)
        {
            List<GradeVsSubject> classSubjects = _context.GradeVsSubject.Where(x => x.GradeId == model.GradeId).ToList();
            foreach (var item in classSubjects)
            {
                if (item.Subject == model.Subject)
                {
                    return false;
                }
                else
                {
                    return true;
                }
            }
            return true;

        }

        public JsonResult GetSubjectList(int grade)
        {
            var dbSubjectList = _context.Subject.Where(x => x.IsActive == (int)IsActive.YES && x.IsDeleted == (int)IsDeleted.NO).ToList();
            var dbClassSubjectList = _context.GradeVsSubject.Where(m => m.Grade.Grade1 == grade).Select(m => m.Subject).ToList();

            foreach (var item in dbClassSubjectList)
            {
                dbSubjectList.Remove(item);
            }
            
            //ViewBag.Subjects = new SelectList(dbSubjectList.AsQueryable(), "Id", "SubjectName");
            TempData["Subjects"] = new SelectList(dbSubjectList.AsQueryable(), "Id", "SubjectName");

            return Json(TempData["Subjects"], JsonRequestBehavior.AllowGet);
        }
    }
}

smart-education-center/Areas/Admin/Views/ManageClass/AddClassPV.cshtml
@model smart_education_center.Models.Grade
@{

    Layout = null;
}
<div class="modal-header site-theme" style="background-color:#343a40">
    <h4 class="modal-title pull-left" style="color:rgba(255, 255, 255, 0.5)">Add a new class</h4>
    <button type="button" class="close" data-dismiss="modal">&times;</button>
</div>
<div class="site-theme">
    @using (Html.BeginForm("AddClass", "ManageClass", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <form id="formAC">
            <div style="padding-right:5px;padding-left:5px;padding-bottom:5px;padding-top:5px; background-color:#ffffff">
                
                <div class="navbar-form div-row" style="position:center">
                    @Html.Label("Grade (Eg: 6)")
                    @Html.TextBoxFor(model => model.Grade1, new { @class = "form-control", @required = "required" })
                </div>
                <div class="navbar-form div-row" style="position:center">
                    @Html.Label("Grade Description")
                    @Html.TextAreaFor(model => model.Grade1, new { @class = "form-control"})
                </div>
            </div>
            <div class="modal-footer site-theme">
                <button type="submit" class="btn btn-success" required>Add</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            </div>
        </form>
    }
</div>

smart-education-center/Areas/Admin/Views/ManageClass/AddSubjectPV.cshtml
@model smart_education_center.Models.Subject
@{

    Layout = null;
}
<div class="modal-header site-theme" style="background-color:#343a40">
    <h4 class="modal-title pull-left" style="color:rgba(255, 255, 255, 0.5)">Add a new subject</h4>
    <button type="button" class="close" data-dismiss="modal">&times;</button>
</div>
<div class="site-theme">
    @using (Html.BeginForm("AddSubject", "ManageClass", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <form id="formAS">
            <div style="padding-right:5px;padding-left:5px;padding-bottom:5px;padding-top:5px; background-color:#ffffff">

                <div class="navbar-form div-row" style="position:center">
                    @Html.Label("Subject (Eg: English)")
                    @Html.TextBoxFor(model => model.SubjectName, new { @class = "form-control", @required = "required" })
                </div>
                <div class="navbar-form div-row" style="position:center">
                    @Html.Label("Subject Code (Eg: ENG)")
                    @Html.TextBoxFor(model => model.SubjectCode, new { @class = "form-control" , @required = "required" })
                </div>
                <div class="navbar-form div-row" style="position:center">
                    @Html.Label("Subject Description")
                    @Html.TextAreaFor(model => model.SubjectDescription, new { @class = "form-control" })
                </div>
            </div>
            <div class="modal-footer site-theme">
                <button type="submit" class="btn btn-success" required>Add</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            </div>
        </form>
    }
</div>

smart-education-center/Areas/Admin/Views/ManageClass/AssignSubjectPV.cshtml
@model smart_education_center.Models.GradeVsSubject
@{
    Layout = null;

}
<div class="modal-header site-theme" style="background-color:#343a40">
    <h4 class="modal-title pull-left" style="color:rgba(255, 255, 255, 0.5)">Assign a subject to a class</h4>
    <button type="button" class="close" data-dismiss="modal">&times;</button>
</div>
<div class="site-theme">
    @using (Html.BeginForm("AssignSubject", "ManageClass", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <form id="formAS">
            <div style="padding-right:5px;padding-left:5px;padding-bottom:5px;padding-top:5px; background-color:#ffffff">

                <div class="navbar-form div-row" style="position:center">
                    @Html.Label("Select the Grade")
                    @Html.DropDownListFor(model => model.GradeId, ViewBag.Grades as SelectList, "--select--", new { @class = "form-control", @required = "required" })
                </div>
                @*<div class="navbar-form div-row" style="position:center">
                    @Html.Label("Select the Subject to assign")
                    <select id="subject_list" class="form-control"></select>
                </div>*@
                
                <div class="navbar-form div-row" style="position:center">
                    @Html.Label("Select the Subject")
                        @Html.DropDownListFor(model => model.SubjectId, ViewBag.Subjects as SelectList, "--select--", new { @class = "form-control", @required = "required" })
                </div>
            </div>
            <div class="modal-footer site-theme">
                <button type="submit" class="btn btn-success" required>Add</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            </div>
        </form>
    }
</div>

<script>
    $(function () {
        $('#Grade_Id').change(function () {
            var option = $(this).find("option:selected").text();
            var url = '@Url.Action("GetSubjectList", "ManageClass")'

            $.ajax({
                url: url,
                type: 'POST',
                dataType: "json",
                data: { grade: parseInt(option) },
                success: function (res) {
                    $.each(res.d, function () {
                        $("#subject_list").append($("<option></option>").val(this.Id).html(this.SubjectName));  
                    }
                )},
                error: function () {
                    alert("error");
                }
            });
        })
    })
</script>

smart-education-center/Areas/Admin/Views/ManageClass/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div id="wrapper">
    <div id="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-4 col-sm-6 mb-3">
                    <div class="card text-white bg-primary o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                                <i class="fas fa-fw fa-comments"></i>
                            </div>
                            <div class="mr-5">6 New Classes!</div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1" href="#" onclick="addView(1)">
                            <span class="float-left">Add a new class</span>
                            <span class="float-right">
                                <i class="fas fa-angle-right"></i>
                            </span>
                        </a>
                    </div>
                </div>
                <div class="col-xl-4 col-sm-6 mb-3">
                    <div class="card text-white bg-warning o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                                <i class="fas fa-fw fa-list"></i>
                            </div>
                            <div class="mr-5">10 New Subjects!</div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1" href="#" onclick="addView(2)">
                            <span class="float-left">Add a new subject</span>
                            <span class="float-right">
                                <i class="fas fa-angle-right"></i>
                            </span>
                        </a>
                    </div>
                </div>
                <div class="col-xl-4 col-sm-6 mb-3">
                    <div class="card text-white bg-success o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                                <i class="fas fa-fw fa-shopping-cart"></i>
                            </div>
                            <div class="mr-5">50+ different subjects from different classes!</div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1" href="#" onclick="addView(3)">
                            <span class="float-left">Assign a subject to a class</span>
                            <span class="float-right">
                                <i class="fas fa-angle-right"></i>
                            </span>
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>


<!--Popup model edit and view-->
<div class="modal fade" id="popupModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body site-theme-model" id="popupModalBodyDiv">
                @*popupPV*@
            </div>
        </div>
    </div>
</div>

<script src="~/Areas/Admin/scripts/jquery.min.js"></script>
<script>

    $(document).ready(function () {

        var resultCode = @Html.Raw(Json.Encode(TempData["ResultCode"]));
        var resultMessage = @Html.Raw(Json.Encode(TempData["ResultMessage"]));

        if (resultCode == 1) {
            toastr.success(resultMessage.toString());
        }

        if (resultCode == 2) {
            toastr.error(resultMessage.toString());
        }
    });

    var addView = function (type) {

        var url = '';
        if (type==1) {
            url = '@Url.Action("AddClass", "ManageClass")';
        }
        if (type==2) {
            url = '@Url.Action("AddSubject", "ManageClass")';
        }
        if (type==3) {
            url = '@Url.Action("AssignSubject", "ManageClass")';
        }

        $("#popupModalBodyDiv").load(url, function () {
            $("#popupModal").modal('show');
        })

    }
</script>